### ISSUE TITLE
Example using anchors?

### ISSUE THREAD

**Issue by jpienaar** [bep/portable-hugo-links#1]
I was trying use render-links example here with anchors, but that doesn't seem to work. For the regular page the relative URL works (yay), but not for those using anchors. Looking at what gets generated I see a nopPage for .relPermalink returned for the link with anchor. 

I'm not sure if there may be some config that is wrong my side, or if relative links with anchors need to be specially handled.

**Comment by bep** [comment]
>I'm not sure if there may be some config that is wrong my side, or if relative links with anchors need to be specially handled.

It should be relatively straight forward to adapt the template to support anchors. A hint if you want to take a stab on it is to use the `urls.Parse` template func to extract the `#` fragment. I will eventually get to it (in a day or two) if not ...

**Comment by jpienaar** [comment]
Sounds good, thanks I was uncertain if it was supported but some of my global configs were stopping it (I've only used Hugo for a couple of days, so all very new still :)). Very nice to have this feature.
