### ISSUE TITLE
Simplification of render-link template

### ISSUE THREAD

**Issue by jhenstridge** [bep/portable-hugo-links#3]
I was playing around with your render-link template, and came up with a somewhat simpler version of the code used to derive the final link value that you might want to use:

```
{{- $link := .Destination }}
{{- $url := urls.Parse $link }}
{{- $isRemote := $url.IsAbs }}
{{- if and (not $isRemote) (strings.HasSuffix $url.Path ".md") }}
  {{- $link = relref .Page $link }}
{{- end -}}
```

Here I'm using the parsed URL to determine whether the link is a local markdown link, and the relref function to convert that to the relative location of that page.  This handles fragments for us, and generates a nice error message if the page cannot be found.

**Comment by bep** [comment]
Thanks.

**Comment by mchubby** [comment]
Interesting but the `(strings.HasSuffix $url.Path ".md")` condition has a side effect:
it prevents linking to list type sections while omitting the `/_index.md` suffix
(uglyURLs = true if that matters)

**Comment by jhenstridge** [comment]
@mchubby: the idea was to only match what looked like direct links to markdown files, and rewrite them to wherever Hugo renders the file.  All other links are left as is.
