### ISSUE TITLE
why isn't this the default Hugo behaviour?

### ISSUE THREAD

**Issue by StefanoCecere** [bep/portable-hugo-links#4]
thank you for this, because i was struggling to edit and manage tons of content via VSCode/Obsidian
and i need to keep markdown readability, so the links have to be kept in md format

but why isn't this a default behaviour? or a config enabled option?

are there any problems if i keep these links?

**Comment by raeperd** [comment]
I cannot agree more @StefanoCecere 
And thanks @bep. Your code saves me tons of times

**Comment by bep** [comment]
>but why isn't this a default behaviour? or a config enabled option?

You need to ask that question in a Hugo forum/tracker.
